python3 submission_runner.py --framework=jax --workload=fastmri --submission_path=prize_qualification_baselines/external_tuning/jax_nadamw_full_budget.py --tuning_search_space=prize_qualification_baselines/external_tuning/tuning_search_space.json --data_dir=/data/fastmri --num_tuning_trials=1 --experiment_dir=/experiment_runs --experiment_name=prize_qualification/study_3 --overwrite=true --save_checkpoints=false --num_tuning_trials=5 --rng_seed=1179630535 --max_global_steps=36189 2>&1 | tee -a /logs/fastmri_jax_01-26-2024-19-13-35.log
I0126 19:13:54.647415 140412669437760 logger_utils.py:76] Creating experiment directory at /experiment_runs/prize_qualification/study_3/fastmri_jax.
I0126 19:13:56.290394 140412669437760 xla_bridge.py:455] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA Interpreter Host
I0126 19:13:56.291143 140412669437760 xla_bridge.py:455] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0126 19:13:56.291293 140412669437760 xla_bridge.py:455] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
I0126 19:13:56.292325 140412669437760 submission_runner.py:542] Using RNG seed 1179630535
I0126 19:13:57.407766 140412669437760 submission_runner.py:551] --- Tuning run 1/5 ---
I0126 19:13:57.407954 140412669437760 submission_runner.py:556] Creating tuning directory at /experiment_runs/prize_qualification/study_3/fastmri_jax/trial_1.
I0126 19:13:57.408134 140412669437760 logger_utils.py:92] Saving hparams to /experiment_runs/prize_qualification/study_3/fastmri_jax/trial_1/hparams.json.
I0126 19:13:57.590423 140412669437760 submission_runner.py:206] Initializing dataset.
I0126 19:14:04.376231 140412669437760 submission_runner.py:213] Initializing model.
I0126 19:14:11.144101 140412669437760 submission_runner.py:255] Initializing optimizer.
I0126 19:14:11.990372 140412669437760 submission_runner.py:262] Initializing metrics bundle.
I0126 19:14:11.990565 140412669437760 submission_runner.py:280] Initializing checkpoint and logger.
I0126 19:14:11.991458 140412669437760 checkpoints.py:915] Found no checkpoint files in /experiment_runs/prize_qualification/study_3/fastmri_jax/trial_1 with prefix checkpoint_
I0126 19:14:11.991613 140412669437760 submission_runner.py:300] Saving meta data to /experiment_runs/prize_qualification/study_3/fastmri_jax/trial_1/meta_data_0.json.
I0126 19:14:11.991798 140412669437760 logger_utils.py:257] Unable to record workload.train_mean information. Continuing without it.
I0126 19:14:11.991864 140412669437760 logger_utils.py:257] Unable to record workload.train_stddev information. Continuing without it.
fatal: detected dubious ownership in repository at '/algorithmic-efficiency'
To add an exception for this directory, call:

	git config --global --add safe.directory /algorithmic-efficiency
I0126 19:14:12.320029 140412669437760 logger_utils.py:220] Unable to record git information. Continuing without it.
I0126 19:14:12.622090 140412669437760 submission_runner.py:304] Saving flags to /experiment_runs/prize_qualification/study_3/fastmri_jax/trial_1/flags_0.json.
I0126 19:14:12.631203 140412669437760 submission_runner.py:314] Starting training loop.
2024-01-26 19:15:09.741086: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2024-01-26 19:15:09.741169: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:1607] failed to query device memory info: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.741181: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 0 bytes free, 0 bytes total.
2024-01-26 19:15:09.741255: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:453] Possibly insufficient driver version: 535.104.5
2024-01-26 19:15:09.741284: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2024-01-26 19:15:09.741357: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2024-01-26 19:15:09.741402: E external/xla/xla/stream_executor/event.cc:34] Error destroying CUDA event: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.741462: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:1607] failed to query device memory info: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.741505: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 6 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.conv.forward' failed: DNN library is not found..
2024-01-26 19:15:09.741518: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 0 bytes free, 0 bytes total.
2024-01-26 19:15:09.741536: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2024-01-26 19:15:09.741613: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:1607] failed to query device memory info: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.741625: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 0 bytes free, 0 bytes total.
2024-01-26 19:15:09.741637: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:1607] failed to query device memory info: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.741681: E external/xla/xla/stream_executor/event.cc:34] Error destroying CUDA event: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.741759: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:453] Possibly insufficient driver version: 535.104.5
2024-01-26 19:15:09.741826: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 0 bytes free, 0 bytes total.
2024-01-26 19:15:09.741842: E external/xla/xla/stream_executor/event.cc:34] Error destroying CUDA event: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.741908: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2024-01-26 19:15:09.742000: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:1607] failed to query device memory info: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.742031: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 0 bytes free, 0 bytes total.
2024-01-26 19:15:09.742049: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:453] Possibly insufficient driver version: 535.104.5
2024-01-26 19:15:09.742093: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:453] Possibly insufficient driver version: 535.104.5
2024-01-26 19:15:09.742116: E external/xla/xla/stream_executor/event.cc:34] Error destroying CUDA event: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.742168: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 4 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.conv.backward.filter' failed: CUDNN_STATUS_EXECUTION_FAILED
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(5333): 'status'.
2024-01-26 19:15:09.742206: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 3 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.conv.forward' failed: DNN library is not found..
2024-01-26 19:15:09.742227: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:453] Possibly insufficient driver version: 535.104.5
2024-01-26 19:15:09.742301: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 7 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.conv.forward' failed: DNN library is not found..
2024-01-26 19:15:09.742356: E external/xla/xla/stream_executor/event.cc:34] Error destroying CUDA event: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.742423: E external/xla/xla/stream_executor/event.cc:34] Error destroying CUDA event: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.742483: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 1 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.conv.forward' failed: DNN library is not found..
2024-01-26 19:15:09.742552: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 2 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.conv.forward' failed: DNN library is not found..
2024-01-26 19:15:09.743015: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2024-01-26 19:15:09.743055: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:1607] failed to query device memory info: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.743067: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 0 bytes free, 0 bytes total.
2024-01-26 19:15:09.743112: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:453] Possibly insufficient driver version: 535.104.5
2024-01-26 19:15:09.743144: E external/xla/xla/stream_executor/event.cc:34] Error destroying CUDA event: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered
2024-01-26 19:15:09.743206: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 5 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.conv.forward' failed: DNN library is not found..
2024-01-26 19:15:19.512580: E external/xla/xla/service/rendezvous.cc:31] This thread has been waiting for 10 seconds and may be stuck:
2024-01-26 19:15:19.743633: F external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2614] Replicated computation launch failed, but not all replicas terminated. Aborting process to work around deadlock. Failure message (there may have been multiple failures, see the error log for all failures): 

Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.conv.forward' failed: DNN library is not found..
Fatal Python error: Aborted

Current thread 0x00007fb45f48a740 (most recent call first):
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/interpreters/pxla.py", line 1346 in __call__
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 314 in wrapper
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 1779 in cache_miss
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 166 in reraise_with_filtered_traceback
  File "/algorithmic-efficiency/prize_qualification_baselines/external_tuning/jax_nadamw_full_budget.py", line 281 in update_params
  File "submission_runner.py", line 336 in train_once
  File "submission_runner.py", line 568 in score_submission_on_workload
  File "submission_runner.py", line 657 in main
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254 in _run_main
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308 in run
  File "submission_runner.py", line 689 in <module>
